name: ALZ-Bicep-1-Core

on:
  push:
    branches:
      - "main"
    paths:
      - "config/custom-parameters/managementGroups.parameters.all.bicepparam"
      - "config/custom-parameters/managementSubscription.parameters.all.bicepparam"
      - "config/custom-parameters/resourceGroupLoggingAndSentinel.parameters.all.bicepparam"
      - "config/custom-parameters/logging.parameters.all.bicepparam"
      - "config/custom-parameters/customPolicyDefinitions.parameters.all.bicepparam"
      - "config/custom-parameters/customRoleDefinitions.parameters.all.bicepparam"
      - "config/custom-parameters/mgDiagSettingsAll.parameters.all.bicepparam"
  pull_request:
    branches:
      - "main"
    paths:
      - "config/custom-parameters/managementGroups.parameters.all.bicepparam"
      - "config/custom-parameters/managementSubscription.parameters.all.bicepparam"
      - "config/custom-parameters/resourceGroupLoggingAndSentinel.parameters.all.bicepparam"
      - "config/custom-parameters/logging.parameters.all.bicepparam"
      - "config/custom-parameters/customPolicyDefinitions.parameters.all.bicepparam"
      - "config/custom-parameters/customRoleDefinitions.parameters.all.bicepparam"
      - "config/custom-parameters/mgDiagSettingsAll.parameters.all.bicepparam"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ENV_FILE: ".env"
  UKS_LOCATION: ${{ vars.UKS_LOCATION }}
  ENV_HUB: ${{ vars.ENV_HUB }}
  TOP_LEVEL_MG_PREFIX: ${{ vars.TOP_LEVEL_MG_PREFIX }}
  UPSTREAM_RELEASE_VERSION: ${{ vars.UPSTREAM_RELEASE_VERSION }}
  MODULES_RELEASE_VERSION: ${{ vars.MODULES_RELEASE_VERSION }}
  INFRA_BILLING_ACCOUNT_NAME: ${{ vars.INFRA_BILLING_ACCOUNT_NAME }}
  INFRA_02_BILLING_PROFILE_NAME: ${{ vars.INFRA_02_BILLING_PROFILE_NAME }}
  INFRA_OPEX_INVOICE_SECTION_NAME: ${{ vars.INFRA_OPEX_INVOICE_SECTION_NAME }}
  AZUREUK: ${{ vars.AZUREUK }}
  AZ_UKSOUTH: ${{ vars.AZ_UKSOUTH }}
  SPACENK_ABBR: ${{ vars.SPACENK_ABBR }}
  PLATFORM_ABBR: ${{ vars.PLATFORM_ABBR }}
  MAN_GRP_NAME: ${{ vars.MAN_GRP_NAME }}
  ID_GRP_NAME: ${{ vars.ID_GRP_NAME }}
  CONN_GRP_NAME: ${{ vars.CONN_GRP_NAME }}
  LOG_ANALYTICS_ABBR_NAME: ${{ vars.LOG_ANALYTICS_ABBR_NAME }}
  IS_PULL_REQUEST: "${{ github.event_name == 'pull_request' }}"

jobs:
  ALZ_Bicep_1_Core:
    runs-on: ubuntu-latest
    environment: SBN-ALZ-Prod
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Remove Quotation Marks from Environment File"
        uses: azure/powershell@v2
        with:
          inlineScript: |
            Write-Host $ENV_FILE
            (Get-Content -Path $env:ENV_FILE -Encoding UTF8) | ForEach-Object {$_ -replace '"',''} | Out-File -FilePath $env:ENV_FILE -Encoding UTF8
          azPSVersion: "latest"

      - name: "Import Environment Variables from File"
        run: cat ${{ env.ENV_FILE }} >> $GITHUB_ENV

      - name: "OIDC Login to Tenant"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.VSDE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: "Management Groups Deployment"
        uses: azure/powershell@v2
        with:
          inlineScript: |
            .\pipeline-scripts\Deploy-ALZManagementGroups.ps1
          azPSVersion: "latest"

      - name: "Deploy Management Subscription for Platform"
        uses: azure/powershell@v2
        with:
          inlineScript: |
            .\pipeline-scripts\Deploy-ALZManagementSubscription.ps1
          azPSVersion: "latest"

      - name: "Logging and Sentinel Resource Group Deployment"
        uses: azure/powershell@v2
        with:
          inlineScript: |
            .\pipeline-scripts\Deploy-ALZLoggingAndSentinelResourceGroup.ps1
          azPSVersion: "latest"

      - name: "Logging and Sentinel Deployment"
        uses: azure/powershell@v2
        with:
          inlineScript: |
            .\pipeline-scripts\Deploy-ALZLoggingAndSentinel.ps1
          azPSVersion: "latest"

      - name: "Custom Policy Definitions Deployment"
        uses: azure/powershell@v2
        with:
          inlineScript: |
            .\pipeline-scripts\Deploy-ALZCustomPolicyDefinitions.ps1
          azPSVersion: "latest"

      - name: "Custom Role Definitions Deployment"
        uses: azure/powershell@v2
        with:
          inlineScript: |
            .\pipeline-scripts\Deploy-ALZCustomRoleDefinitions.ps1
          azPSVersion: "latest"

      - name: "Custom Management Group Diagnostic Settings"
        uses: azure/powershell@v2
        with:
          inlineScript: |
            .\pipeline-scripts\Deploy-ALZMGDiagnosticSettings.ps1
          azPSVersion: "latest"
          