name: ALZ-Bicep-1-Core-Test

on:
  push:
    branches:
      - "main"
    paths:
      - "config/custom-parameters/managementGroups.parameters.all.bicepparam"
  pull_request:
    branches:
      - "main"
    paths:
      - "config/custom-parameters/managementGroups.parameters.all.bicepparam"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ENV_FILE: ".env"
  IS_PULL_REQUEST: "${{ github.event_name == 'pull_request' }}"

jobs:
  ALZ_Bicep_1_Core_Test:
    runs-on: ubuntu-latest
    environment: SBN-ALZ-Prod
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Remove Quotation Marks from Environment File"
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Write-Host $ENV_FILE
            (Get-Content -Path $env:ENV_FILE -Encoding UTF8) | ForEach-Object {$_ -replace '"',''} | Out-File -FilePath $env:ENV_FILE -Encoding UTF8
          azPSVersion: "latest"

      - name: Import Environment Variables from File
        run: cat ${{ env.ENV_FILE }} >> $GITHUB_ENV

      - name: OIDC Login to Tenant
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.VSDE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: "Management Groups Deployment"
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\pipeline-scripts\Deploy-ALZManagementGroups.ps1 -TemplateParameterFile .\config\custom-parameters\managementGroups.parameters.all.bicepparam
          azPSVersion: "latest"